name: Get lastest open data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 2" # At 08:00 on Tuesday GMT+2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install
      - name: Run script to download latest open data
        run: npm run cron
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update open data